version: "3.4"

# TODO: Can I reuse and interpolate username and password?
services:
  mongo:
    image: mongo:6.0.13
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    links: 
      - mongo:mongo
    environment:
      # TODO: WTF? For some reason user/pass are admin/pass even
      # though I did set them?
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
